# This workflow will install Python dependencies and run tests with LlamaIndex

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    environment: Actions
    defaults:
      run: 
        shell: bash
        working-directory: ./rag-tonic-demo-oxford

    steps:
    # - name: set pythonpath
    #   run: | #trying this!
    #     echo "PYTHONPATH=/home/runner/work/rag-tonic-demo/rag-tonic-demo/rag-tonic-demo-oxford" >> $GITHUB_ENV 
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry config virtualenvs.create false
        poetry install --no-root --no-dev --no-directory
    - name: Set PYTHONPATH
      #run: echo "PYTHONPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV
      run: echo "export PYTHONPATH=$PYTHONPATH:/home/runner/work/rag-tonic-demo/rag-tonic-demo/rag-tonic-demo-oxford" >> $GITHUB_ENV
      # run: |
      #   python -c "import sys; sys.path.append('.'); print(sys.path)"
    - name: Set up vector index
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        python app/engine/generate.py
    - name: Start up test server
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        MODEL: gpt-3.5-turbo #gpt-4-1106-preview
      run: |
        python main.py &
        sleep 10
    - name: Test with pytest
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        TONIC_VALIDATE_API_KEY: ${{ secrets.TONIC_VALIDATE_API_KEY }}
        PROJECT_ID: ${{ secrets.PROJECT_ID }}
      run: |
        pytest